### ISSUE TITLE
Unittest don't build with DMD 2.088 and up (don't know the actual fail point)

### ISSUE THREAD

**Issue by JesseKPhillips** [JakobOvrum/LuaD#112]
Rather than accepting the C function as a LuaFunction, it is trying to convert the lua_state* argument.

I'm slightly leaning toward the attributes being assigned "pure nothrow @nogc @safe"

> luad/stack.d(183,3): Error: static assert: "No Lua type defined for lua_State*"
luad/stack.d(224,23): instantiated from here: luaTypeOf!(lua_State*)
luad/stack.d(378,10): instantiated from here: getValue!(lua_State*, argumentTypeMismatch)
luad/conversions/functions.d(215,13): instantiated from here: getArgument!(extern (C) int function(lua_State*) pure nothrow @nogc @safe, 0)
luad/conversions/functions.d(248,23): ... (1 instantiations, -v to show) ...
luad/stack.d(133,15): instantiated from here: pushFunction!(extern (C) int function(lua_State*) pure nothrow @nogc @safe)
luad/stack.d(626,11): instantiated from here: pushValue!(extern (C) int function(lua_State*) pure nothrow @nogc @safe)
